# Generated by Django 4.2.21 on 2025-05-25 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0007_alter_cartitem_cart'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),

    ]
