# Generated by Django 4.2.21 on 2025-06-01 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0010_alter_orderdetail_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paymentMethod',
            field=models.IntegerField(choices=[(1, 'Thanh toán bằng tiền mặt'), (2, 'Thanh toán bằng ví điện tử')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
