# Generated by Django 4.2.21 on 2025-06-01 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0011_order_paymentmethod_user_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orderMethod',
            field=models.IntegerField(choices=[(1, 'Chờ xác nhận'), (2, 'Đã xác nhận'), (3, 'Đã bị hủy'), (4, 'Đang được giao'), (5, 'Bị hủy do thanh toán thất bại'), (6, 'Đơn hàng đã được giao')], default=1),
            preserve_default=False,
        ),
    ]
