# Generated by Django 4.2.21 on 2025-06-01 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0012_order_ordermethod'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='orderMethod',
            new_name='status',
        ),
    ]
