# Generated by Django 4.2.21 on 2025-06-02 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0014_orderdetail_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='paymentMethod',
            new_name='payment_method',
        ),
    ]
