# Generated by Django 4.2.21 on 2025-06-04 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0017_user_created_date_user_updated_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
