# Generated by Django 4.2.21 on 2025-06-05 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0019_alter_payment_options_remove_payment_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='amount',
        ),
    ]
