# Generated by Django 4.2.21 on 2025-06-06 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0020_remove_payment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='request_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[(0, 'Cash On Delivery'), (1, 'MoMo')], max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[(0, 'Pending'), (1, 'Completed'), (2, 'Failed')], default=0, max_length=20),
        ),
    ]
