# Generated by Django 4.2.21 on 2025-06-06 07:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0021_payment_request_id_alter_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 6, 7, 31, 55, 884047, tzinfo=datetime.timezone.utc)),
        ),
    ]
