# Generated by Django 4.2.21 on 2025-06-06 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0020_product_sold_product_stock'),
        ('commerce', '0022_alter_payment_created_date'),
    ]

    operations = [
    ]
