# Generated by Django 4.2.21 on 2025-06-06 19:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0022_alter_payment_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 6, 19, 54, 37, 219452, tzinfo=datetime.timezone.utc)),
        ),
    ]
