# Generated by Django 4.2.21 on 2025-06-06 22:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0023_alter_payment_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 6, 22, 28, 21, 322004, tzinfo=datetime.timezone.utc)),
        ),
    ]
