# Generated by Django 4.2.21 on 2025-06-07 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0023_merge_20250606_2317'),
        ('commerce', '0025_remove_payment_method_payment_amount_and_more'),
    ]

    operations = [
    ]
