# Generated by Django 4.2.21 on 2025-06-07 03:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0026_merge_20250607_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.IntegerField(choices=[(0, 'Cash On Delivery'), (1, 'MoMo')], default=0),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Completed'), (2, 'Failed')], default=0),
        ),
    ]
